/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Password */
        put: operations["change_password_api_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogs */
        get: operations["catalogs_api_catalogos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proyectos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_proyectos_get"];
        put?: never;
        /** Create */
        post: operations["create_api_proyectos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proyectos/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_proyectos__identifier__get"];
        /** Update */
        put: operations["update_api_proyectos__identifier__put"];
        post?: never;
        /** Remove */
        delete: operations["remove_api_proyectos__identifier__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proyectos/{identifier}/tareas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_proyectos__identifier__tareas_get"];
        put?: never;
        /** Create */
        post: operations["create_api_proyectos__identifier__tareas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tareas/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_tareas__identifier__get"];
        /** Update */
        put: operations["update_api_tareas__identifier__put"];
        post?: never;
        /** Remove */
        delete: operations["remove_api_tareas__identifier__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consumos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_consumos_get"];
        put?: never;
        /** Create */
        post: operations["create_api_consumos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consumos/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_consumos__identifier__get"];
        /** Update */
        put: operations["update_api_consumos__identifier__put"];
        post?: never;
        /** Remove */
        delete: operations["remove_api_consumos__identifier__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proyectos/{identifier}/reporte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_proyectos__identifier__reporte_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recursos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_recursos_get"];
        put?: never;
        /** Create */
        post: operations["create_api_recursos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recursos/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_recursos__identifier__get"];
        /** Update */
        put: operations["update_api_recursos__identifier__put"];
        post?: never;
        /** Remove */
        delete: operations["remove_api_recursos__identifier__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_roles_get"];
        put?: never;
        /** Create */
        post: operations["create_api_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_roles__identifier__get"];
        /** Update */
        put: operations["update_api_roles__identifier__put"];
        post?: never;
        /** Remove */
        delete: operations["remove_api_roles__identifier__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alertas/ejecutar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_api_alertas_ejecutar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carga-masiva/{entidad}/plantilla.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template */
        get: operations["template_api_carga_masiva__entidad__plantilla_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carga-masiva/{entidad}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_carga_masiva__entidad__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertResult */
        AlertResult: {
            /**
             * Fecha
             * Format: date
             */
            fecha: string;
            /**
             * Vencidos
             * @default 0
             */
            vencidos: number;
            /**
             * Enviados
             * @default 0
             */
            enviados: number;
            /**
             * Fallidos
             * @default 0
             */
            fallidos: number;
            /**
             * Sin Email
             * @default 0
             */
            sin_email: number;
            /**
             * En Ejecucion
             * @default false
             */
            en_ejecucion: boolean;
        };
        /** Body_upload_api_carga_masiva__entidad__post */
        Body_upload_api_carga_masiva__entidad__post: {
            /** Archivo */
            archivo?: string | null;
        };
        /** CargaIssue */
        CargaIssue: {
            /** Fila */
            fila: number;
            /** Campo */
            campo?: string | null;
            /** Mensaje */
            mensaje: string;
        };
        /** CargaResultado */
        CargaResultado: {
            /** Entidad */
            entidad: string;
            /** Total */
            total: number;
            /** Validas */
            validas: number;
            /** Errores Total */
            errores_total: number;
            /** Errores */
            errores: components["schemas"]["CargaIssue"][];
            /** Advertencias */
            advertencias: components["schemas"]["CargaIssue"][];
            /** Creadas */
            creadas: number;
            /** Confirmada */
            confirmada: boolean;
        };
        /** Catalogos */
        Catalogos: {
            /** Estados */
            estados: string[];
            /** Recursos */
            recursos: components["schemas"]["RecursoRef"][];
            /** Roles */
            roles: components["schemas"]["RolOut"][];
        };
        /** ConsumoIn */
        ConsumoIn: {
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Proyecto Id */
            proyecto_id: number;
            /** Recurso Id */
            recurso_id?: number | null;
            /** Horas Consumidas */
            horas_consumidas: number;
            /** Tarea */
            tarea: string;
            /** Rol Id */
            rol_id: number;
        };
        /** ConsumoListado */
        ConsumoListado: {
            /** Consumo Id */
            consumo_id: number;
            /** Proyecto Id */
            proyecto_id: number;
            /** Recurso Id */
            recurso_id: number;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Horas Consumidas */
            horas_consumidas: number;
            /** Tarea */
            tarea: string;
            /** Rol Id */
            rol_id: number;
            /** Proyecto Nombre */
            proyecto_nombre: string;
            /** Recurso Nombre */
            recurso_nombre: string;
            /** Rol Descripcion */
            rol_descripcion: string;
        };
        /** ConsumoOut */
        ConsumoOut: {
            /** Consumo Id */
            consumo_id: number;
            /** Proyecto Id */
            proyecto_id: number;
            /** Recurso Id */
            recurso_id: number;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Horas Consumidas */
            horas_consumidas: number;
            /** Tarea */
            tarea: string;
            /** Rol Id */
            rol_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /** Recurso Nombre */
            recurso_nombre: string;
            /** Password */
            password: string;
        };
        /** PasswordIn */
        PasswordIn: {
            /** Actual */
            actual: string;
            /** Password */
            password: string;
            /** Confirmacion */
            confirmacion: string;
        };
        /** ProyectoDetalle */
        ProyectoDetalle: {
            proyecto: components["schemas"]["ProyectoResumen"];
            /** Consumos */
            consumos: components["schemas"]["ConsumoListado"][];
            /** Por Recurso */
            por_recurso: {
                [key: string]: number;
            };
            /** Por Rol */
            por_rol: {
                [key: string]: number;
            };
        };
        /** ProyectoIn */
        ProyectoIn: {
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Proyecto Nombre */
            proyecto_nombre: string;
            /** Horas Requeridas */
            horas_requeridas: number;
            /** Owner Id */
            owner_id?: number | null;
            /** Proyect Status */
            proyect_status: string;
            /** Porcentaje Avance */
            porcentaje_avance: number;
        };
        /** ProyectoOut */
        ProyectoOut: {
            /** Proyecto Id */
            proyecto_id: number;
            /** Proyecto Nombre */
            proyecto_nombre: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Horas Requeridas */
            horas_requeridas: number;
            /** Owner Id */
            owner_id: number;
            /** Proyect Status */
            proyect_status: string;
            /** Porcentaje Avance */
            porcentaje_avance: number;
        };
        /** ProyectoReporte */
        ProyectoReporte: {
            proyecto: components["schemas"]["ProyectoResumen"];
            /**
             * Fecha Corte
             * Format: date
             */
            fecha_corte: string;
            /**
             * Periodo
             * @enum {string}
             */
            periodo: "semana" | "mes";
            salud: components["schemas"]["ReporteSalud"];
            /** Periodos */
            periodos: components["schemas"]["ReportePeriodo"][];
            ritmo: components["schemas"]["ReporteRitmo"];
            ejecucion: components["schemas"]["ReporteEjecucion"];
            tareas: components["schemas"]["ReporteTareas"];
            distribucion: components["schemas"]["ReporteDistribucion"];
        };
        /** ProyectoResumen */
        ProyectoResumen: {
            /** Proyecto Id */
            proyecto_id: number;
            /** Proyecto Nombre */
            proyecto_nombre: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Horas Requeridas */
            horas_requeridas: number;
            /** Owner Id */
            owner_id: number;
            /** Proyect Status */
            proyect_status: string;
            /** Porcentaje Avance */
            porcentaje_avance: number;
            /** Responsable */
            responsable: string;
            /** Horas Consumidas */
            horas_consumidas: number;
            /** Saldo */
            saldo: number;
            /** Exceso */
            exceso: number;
            /** Porcentaje Consumo */
            porcentaje_consumo: number;
        };
        /** RecursoIn */
        RecursoIn: {
            /** Email */
            email?: string | null;
            /** Recurso Nombre */
            recurso_nombre: string;
            /**
             * Es Admin
             * @default false
             */
            es_admin: boolean;
            /**
             * Password
             * @default
             */
            password: string;
        };
        /** RecursoRef */
        RecursoRef: {
            /** Recurso Id */
            recurso_id: number;
            /** Recurso Nombre */
            recurso_nombre: string;
        };
        /** ReporteDistribucion */
        ReporteDistribucion: {
            /** Por Recurso */
            por_recurso: components["schemas"]["ReporteParte"][];
            /** Por Rol */
            por_rol: components["schemas"]["ReporteParte"][];
            /** Actividades */
            actividades: components["schemas"]["ReporteParte"][];
        };
        /** ReporteEjecucion */
        ReporteEjecucion: {
            /** Primer Consumo */
            primer_consumo: string | null;
            /** Ultimo Consumo */
            ultimo_consumo: string | null;
            /** Dias Desvio Inicio */
            dias_desvio_inicio: number | null;
            /** Horas Antes Inicio */
            horas_antes_inicio: number;
            /** Horas Despues Fin */
            horas_despues_fin: number;
            /** Dias Con Actividad */
            dias_con_actividad: number;
            /** Dias Transcurridos */
            dias_transcurridos: number;
        };
        /** ReporteParte */
        ReporteParte: {
            /** Nombre */
            nombre: string;
            /** Horas */
            horas: number;
            /** Porcentaje */
            porcentaje: number;
        };
        /** ReportePeriodo */
        ReportePeriodo: {
            /**
             * Desde
             * Format: date
             */
            desde: string;
            /**
             * Hasta
             * Format: date
             */
            hasta: string;
            /** Horas */
            horas: number;
            /** Por Rol */
            por_rol: {
                [key: string]: number;
            };
            /** Por Recurso */
            por_recurso: {
                [key: string]: number;
            };
        };
        /** ReporteRitmo */
        ReporteRitmo: {
            /** Horas Semana Reciente */
            horas_semana_reciente: number;
            /** Horas Semana Promedio */
            horas_semana_promedio: number;
            /** Horas Semana Necesarias */
            horas_semana_necesarias: number | null;
            /** Dias Restantes */
            dias_restantes: number;
        };
        /** ReporteSalud */
        ReporteSalud: {
            /** Porcentaje Tiempo */
            porcentaje_tiempo: number;
            /** Porcentaje Consumo */
            porcentaje_consumo: number;
            /** Porcentaje Avance */
            porcentaje_avance: number;
            /** Horas Ganadas */
            horas_ganadas: number;
            /** Indice Eficiencia */
            indice_eficiencia: number | null;
            /** Estado Eficiencia */
            estado_eficiencia: ("bien" | "atencion" | "critico") | null;
            /** Indice Cronograma */
            indice_cronograma: number | null;
            /** Estado Cronograma */
            estado_cronograma: ("bien" | "atencion" | "critico") | null;
        };
        /** ReporteTareas */
        ReporteTareas: {
            /** Total */
            total: number;
            /** Completadas */
            completadas: number;
            /** En Curso */
            en_curso: number;
            /** Sin Recurso */
            sin_recurso: number;
            /** Vencidas */
            vencidas: components["schemas"]["TareaOut"][];
            /** Sin Iniciar Atrasadas */
            sin_iniciar_atrasadas: components["schemas"]["TareaOut"][];
            /** Avance Planificado */
            avance_planificado: number;
            /** Avance Real */
            avance_real: number;
        };
        /** RolIn */
        RolIn: {
            /** Rol Descripcion */
            rol_descripcion: string;
        };
        /** RolOut */
        RolOut: {
            /** Rol Id */
            rol_id: number;
            /** Rol Descripcion */
            rol_descripcion: string;
        };
        /** SesionOut */
        SesionOut: {
            user: components["schemas"]["UsuarioOut"] | null;
            /** Csrf Token */
            csrf_token: string;
        };
        /** TareaIn */
        TareaIn: {
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Tarea Nombre */
            tarea_nombre: string;
            /** Porcentaje Avance */
            porcentaje_avance: number;
            /** Recurso Id */
            recurso_id?: number | null;
        };
        /** TareaOut */
        TareaOut: {
            /** Tarea Id */
            tarea_id: number;
            /** Proyecto Id */
            proyecto_id: number;
            /** Tarea Nombre */
            tarea_nombre: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Porcentaje Avance */
            porcentaje_avance: number;
            /** Recurso Id */
            recurso_id: number | null;
            /** Recurso Nombre */
            recurso_nombre: string | null;
        };
        /** UsuarioOut */
        UsuarioOut: {
            /** Email */
            email?: string | null;
            /** Recurso Id */
            recurso_id: number;
            /** Recurso Nombre */
            recurso_nombre: string;
            /** Es Admin */
            es_admin: boolean;
            /** Debe Cambiar Password */
            debe_cambiar_password: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    current_session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionOut"];
                };
            };
        };
    };
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionOut"];
                };
            };
        };
    };
    change_password_api_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogs_api_catalogos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogos"];
                };
            };
        };
    };
    index_api_proyectos_get: {
        parameters: {
            query?: {
                estado?: string;
                responsable?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProyectoResumen"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_proyectos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProyectoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProyectoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_proyectos__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProyectoDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_proyectos__identifier__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProyectoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProyectoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_proyectos__identifier__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_proyectos__identifier__tareas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TareaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_proyectos__identifier__tareas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TareaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TareaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_tareas__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TareaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_tareas__identifier__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TareaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TareaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_tareas__identifier__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_consumos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumoListado"][];
                };
            };
        };
    };
    create_api_consumos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_consumos__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_consumos__identifier__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_consumos__identifier__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_proyectos__identifier__reporte_get: {
        parameters: {
            query?: {
                periodo?: string;
            };
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProyectoReporte"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_recursos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"][];
                };
            };
        };
    };
    create_api_recursos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecursoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_recursos__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_recursos__identifier__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecursoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_recursos__identifier__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolOut"][];
                };
            };
        };
    };
    create_api_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_roles__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_roles__identifier__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_roles__identifier__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_api_alertas_ejecutar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResult"];
                };
            };
        };
    };
    template_api_carga_masiva__entidad__plantilla_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_carga_masiva__entidad__post: {
        parameters: {
            query?: {
                confirmar?: boolean;
            };
            header?: never;
            path: {
                entidad: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_carga_masiva__entidad__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargaResultado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
